<?php
$userData = [
  'id' => 'xxxxx',
  'displayName' => 'xxxxx',
  'email' => 'xxxxx',
  'photoURL' => 'xxxxx',
  'avatarColor' => 'xxxxx',
  'organizations' => ['xxxxx'],
  'clientsDisplay' => ['xxxxx'],
  'dateLastLogin' => (new \DateTime())->format('Y-m-d H:i:s'),
];

$domainData = [
  'id' => 'xxxxx',
  'name' => 'xxxxx',
  'organization' => 'xxxxx',
  'domain' => 'xxxxx',
  'hostname' => 'xxxxx',
  'homepageRedirectUrl' => 'xxxxx',
  'cNameVerification' => 'xxxxx',
  'cNameDomain' => 'xxxxx',
  'isProcessing' => false,
  'status' => 'xxxxx',
  'isActive' => true,
  'isDeleted' => false,
  'validationDate' => (new \DateTime())->format('Y-m-d H:i:s'),
  'firstChecked' => (new \DateTime())->format('Y-m-d H:i:s'),
];

$organizationData = [
  'id' => 'xxxxx',
  'name' => 'xxxxx',
  'logoUrl' => 'xxxxx',
  'domain' => $domainData,
  'backgroundColor' => 'xxxxx',
  'favIcon16' => 'xxxxx',
  'favIcon32' => 'xxxxx',
  'favIcon48' => 'xxxxx',
  'favIcon120' => 'xxxxx',
  'favIcon240' => 'xxxxx',
  'defaultProximityUUID' => 'xxxxx',
  'termsHtml' => 'xxxxx',
  'privacyHtml' => 'xxxxx',
  'headerPixels' => 'xxxxx',
  'footerPixels' => 'xxxxx',
  'owner' => 'xxxxx',
  'admins' => ['xxxxx'],
  'editors' => ['xxxxx'],
  'joinCode' => 'xxxxx'
];

$templateData = [
  'id' => 'xxxxx',
  'name' => 'xxxxx',
  'version' => 1,
  'versionID' => 'xxxxx',
  'files' => ['xxxxx'],
  'templateUrls' => ['xxxxx'],
  'apple' => ['xxxxx'],
  'google' => ['xxxxx'],
  'organization' => $organizationData,
  'folder' => 'xxxxx',
  'sessionId' => 'xxxxx',
  'screenshotUrl' => 'xxxxxx',
  'screenshotAppleUrl' => 'xxxxxx',
  'screenshotAndroidUrl' => 'xxxxxx',
  'pdfUrl' => 'xxxxxx',
  'pdfAppleUrl' => 'xxxxxx',
  'pdfAndroidUrl' => 'xxxxxx',
  'updatedDate' => (new \DateTime())->format('Y-m-d H:i:s'),
  'isPublicShare' => false,
  'status' => 'xxxxxx',
  'assignee' => $userData,
  'createdBy' => $userData,
  'labels' => ['xxxxxx'],
];

$scheduleData = [
  'when' => ['xxxxxx'],
  'weekday' => 'xxxxxx',
  'monthday' => 'xxxxxx',
  'time' => 'xxxxxx',
];

$statsData = [
  'id' => 'xxxxx',
  'countMacType' => 1,
  'countWindowsType' => 1,
  'countLinuxType' => 1,
  'countMobileType' => 1,
  'countDesktopType' => 1,
  'countWearableType' => 1,
  'countTabletType' => 1,
  'countAndroidType' => 1,
  'countIOSType' => 1,
  'countWinPhoneType' => 1
];

$campaignData = [
  'id' => 'xxxxxx',
  'name' => 'xxxxxx',
  'organization' => $organizationData,
  'template' => $templateData,
  'schedule' => $scheduleData,
  'stats' => $statsData,
  'landingPage' => 'xxxxxx',
  'primaryKey' => 'xxxxxx',
  'description' => 'xxxxxx',
  'headerPixels' => 'xxxxxx',
  'footerPixels' => 'xxxxxx',
  'openEnrollment' => 'xxxxxx',
  'openEnrollmentLandingPage' => 'xxxxxx',
  'openEnrollmentPermalink' => 'xxxxxx',
  'openEnrollmentJwtSecret' => 'xxxxxx',
  'importConfig' => ['xxxxxx'],
  'exportConfig' => ['xxxxxx'],
  'importDataSource' => 'xxxxxx',
  'exportDataSource' => 'xxxxx',
  'templateCurrentChangeDate' => (new \DateTime())->format('Y-m-d H:i:s'),
  'folder' => 'xxxxxx',
  'browsers' => ['xxxxxx'],
  'countries' => ['xxxxxx'],
  'states' => ['xxxxxx'],
  'runningDate' => (new \DateTime())->format('Y-m-d H:i:s'),
  'jobNotifications' => 'xxxxxx',
  'passesCount' => 1,
  'claimedCount' => 1,
  'registeredCount' => 1,
  'enrolledCount' => 1,
  'isDeleted' => false,
  'passTypeIdentifier' => 'xxxxxx',
  'googleIssuer' => 'xxxxxx',
];
